sudo: required
dist: trusty
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install python-sphinx
  - which python
  - python --version
  - which pip

install:
  - pip install http://download.pytorch.org/whl/cpu/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision
  - pip install -r requirements.txt
  - pip install codecov
  - pip install recommonmark
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - python setup.py install
  - pip install --upgrade pytest

cache:
  pip: true

env:
  global:
  - COLUMNS=80
  - secure: "Qd2sF/ZjKyYMO/DGl0qznbmTjtSy6XnUjAQgMe1Bn3XtHBSYPTN0vrR043s/mhxE+ltoHoP8tG7QVYZiJQJnYxEHJQO0+r0phM7sA4Qjbx0LxUryCCDQIUOcjRhMwATEtOnwPDfNq4nZsl00UwK4ag/JjfpZR8TBGn6bGY2PhZePLkmO4L6uGGAEygQQ/LQsB/bmh3C0Ks4EibNMqz8CB43VNQX/qHpXrZaMMQEgbaR+gUXqdSoHqzYSKqZ359dsodcCTRHHfhN2r4IxIpZP1Iizq0jflxgXf4f4WJ96y3v2MAmpP56IORXi5mu2AOVpZFSGn91rJIrvFGJowPS2+Stb8W7G8alG0ac3nppJv34N9RjBfpcFly8hybhiEebHkQf+vuiV4wvw593OnZ36hRzBffyx4qq2QZ/BcarAgbnWqtG7VxVumoiRuWL4caaGaWd4gByu/p76nkLcSC4G7RAzXW0QsEe295nQgS1qIEWSCBBz2USl0DNkzJIBKhHZCL+md6lePtItpLFd13ZtS5FRGUUhJe+erbVV8OwxqcP/XPuGwYFPAPMQLULZ8Tm3UL1ta+lRGSDNc/hddkA15/gqVX7ZLdjShrU2Omk4DfH748pSfroJtklT7Yz6Ep9Z10a2+rXAzds6JxMjShrIdR2Tv9Kkh21C/60Tx+cydr8="

python:
  - '3.6'

script:
  - coverage run --source=ganzoo setup.py test
  - coverage report
  - set -e
  - pwd
  - cd docs
  - make html
  - cd ..
  - pip install doctr
  - doctr deploy .
  - pytest

after_success:
  - codecov

deploy:
  provider: pypi
  user: innerlee
  password:
    secure: MVrf7maVaYu8SX6jSeI1edTfimd2Ia+705kBboyDrHEW0NHLV52M0hXCUq/4XUKoA+fBUxwFcTeIMGpRW1uRHt88roNuEREo40yLfjMHTW9vvx0nDyLFuvtu4HoXbWyFKBMfebAJJbn9orjX3eQC5gu4TUw0jDOMGPOoCqne7wiRlJTX7YufBIRggIkpIE5lbimZuM9vUB8at/BZbnKehZibzrdwHia5vSOHfQL6QFpmNR1fwqF/CPlBCujvaFvY14TxGMDbxQ9K44fPgxOhy3CLDcW5FHIcEgkQafg9oDqFpXGxSuqmLSXb/dhBIiNKrvppI23NKjCjkwhuCSVtkni1B1+j+wgsDDfVe7UCjQLyLlBwfFdSEQjDkBAZ7wgBRk7ovJTH7jqvCYge7Hojm1PEgqoq0X7YKUDNFrOxv/1aeWkpWzhC/O/0zdBmoeXCMaaumGG4GALbg8Oc/AiJE+V2afM/41djRUVkJZT8gjoAgOS+iYXJoa1etGvnrJTYVd3mXymg2472zJWjS1rAzq2ZpdDZnl8+9i3/E/R8smSpqEW9lNKDxnxhbghf+jfz1TSE3QrCRHJkoRO/JGCJsY4mH5ZlEnvox9J658cHN9FxC1tN0wO1Yf/hjQqvC1jEFqM6w4QIjScVzu/JtxNSsBthdHkgzPt1MFJRPTW6ytE=
  on:
    branch: master
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
